<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AcmeHttp</RootNamespace>
    <AssemblyName>AcmeHttp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BeaconTower.ProviderSdk" Version="3.9.3" />
  </ItemGroup>

</Project>
